version: "1.0"
info:
  model: int-scaffold
packages:
- name: TDolbyACEcfIWHIProject
  gitServerName: tdolby
  gitUrl: https://github.com/trevor-dolby-at-ibm-com
  gitUsername: trevor-dolby-at-ibm-com
  gitBranch: main
